# Generated by Django 4.0.5 on 2022-06-21 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_alter_razorpaycustomer_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpayorderid',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='amount_due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='customer',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='merchant',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='notes1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='notes2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='order_id',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
