# Generated by Django 4.0.5 on 2022-06-21 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_razorpayorderid_amount_razorpayorderid_amount_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorderid',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
