# Generated by Django 4.0.5 on 2022-06-21 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_razorpayorderid_created_razorpayorderid_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpayorderid',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='razorpayorderid',
            name='merchant',
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='payer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razorpayorderid',
            name='receiver',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
