# Generated by Django 4.0.5 on 2022-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_razorpayorderid_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorderid',
            name='order_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='razorpayorderid',
            name='payer',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='razorpayorderid',
            name='receiver',
            field=models.CharField(max_length=25),
        ),
    ]
