# Generated by Django 4.0.4 on 2022-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='first_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
